### ISSUE TITLE
Unable to resolve "../assets/images.js"

### ISSUE THREAD

**Issue by SabreCat** [FifteenFifty/PoELevellingCompanion#5]
Attempted to run this locally but it's erroring out.

1. Clone the repo
2. npm i
3. npm start
4. Scan QR code, or click "run in web browser" in Metro Bundler

Result:
![image](https://user-images.githubusercontent.com/4501321/84683080-46bcee80-aefc-11ea-857b-290225773f95.png)

**Comment by SabreCat** [comment]
Looks like the trouble occurs here: https://github.com/FifteenFifty/PoELevellingCompanion/blob/29781e2736c844b4f2f55a8768aa7649550965bd/screens/about.js#L5

Possibly a file that was meant to be added in 43b2670c5569d9ea07229ddde70 but was left out by mistake?

**Comment by FifteenFifty** [comment]
Thanks for reporting this! Just pushed the file

**Comment by SabreCat** [comment]
That did it, thanks!
